{% set version = "3.02" %}

package:
  name: pyorac
  version: {{ version }}

source:
  - git_url: https://github.com/ORAC-CC/orac
  - path: local_defaults.py
    folder: tools/pyorac/local_defaults.py

build:
  number: 2
  script: cd tools && {{ PYTHON }} -m pip install . -vv
  run_exports:
    - {{ pin_subpackage('pyorac', max_pin='x.x') }}

requirements:
  host:
    - python
    - cartopy
    - cf-units
    - h5py
    - matplotlib
    - netcdf4
    - numpy
    - opencv
    - orac 4.11
    - scipy
  run:
    - python
    - cartopy
    - cf-units
    - h5py
    - matplotlib
    - netcdf4
    - {{ pin_compatible('numpy') }}
    - opencv
    - orac 4.11
    - scipy

test:
  commands:
    - orac.py -h
    - regression.py -h
    - single_process.py -h

about:
  home: https://github.com/ORAC-CC/orac/wiki
  license: CC
  license_file: COPYING
  summary: 'Scripts to call the Optimal Retrieval of Aerosol and Cloud'

extra:
  recipe-maintainers:
    - orac_cc
