{% set version = "2.3" %}

package:
  name: epr_api
  version: {{ version }}

source:
  git_url: https://github.com/bcdev/epr-api
  patches:
    - makefile.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('epr_api', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake

test:
  requires:
    - {{ compiler('c') }}
  files:
    - write_bands.c
  commands:
    - test -f ${PREFIX}/lib/libepr_api.a
    - ${GCC} -o example -I${PREFIX}/include write_bands.c -L${PREFIX}/lib -lepr_api

about:
  home: http://github.com/bcdev/epr-api
  license: GPL
  summary: 'Library supporting products of the ESA ENVISAT satellite'

extra:
  recipe-maintainers:
    - orac_cc
