# This is the CMakeCache file.

########################
# EXTERNAL cache entries
########################

SET (BUILD_SHARED_LIBS ON CACHE BOOL "Build Shared Libraries" FORCE)

SET (USE_SHARED_LIBS ON CACHE BOOL "Use Shared Libraries" FORCE)

SET (BUILD_TESTING ON CACHE BOOL "Build HDFEOS Unit Testing" FORCE)

SET (HDFEOS_PACKAGE_EXT "" CACHE STRING "Name of HDF package extension" FORCE)

SET (HDFEOS_BUILD_SAMPLES ON CACHE BOOL "Build HDFEOS Library Samples" FORCE)

SET (HDFEOS_BUILD_TESTDRIVERS ON CACHE BOOL "Build HDFEOS Testdrivers" FORCE)

SET (HDFEOS_ENABLE_JPEG_LIB_SUPPORT ON CACHE BOOL "Enable Jpeg library" FORCE)

SET (HDFEOS_ENABLE_Z_LIB_SUPPORT ON CACHE BOOL "Enable Zlib Filters" FORCE)

SET (HDFEOS_ENABLE_SZIP_SUPPORT ON CACHE BOOL "Use SZip Filter" FORCE)

SET (HDFEOS_ENABLE_SZIP_ENCODING ON CACHE BOOL "Use SZip Encoding" FORCE)

SET (HDFEOS_DISABLE_COMPILER_WARNINGS ON CACHE BOOL "Disable compiler warnings" FORCE)

SET (HDFEOS_ENABLE_PARALLEL OFF CACHE BOOL "Enable parallel build (requires MPI)" FORCE)

SET (HDFEOS_BUILD_FORTRAN ON CACHE BOOL "Enable fortran for Programs" FORCE)

SET (HDFEOS_PACKAGE_EXTLIBS OFF CACHE BOOL "(WINDOWS)CPACK - include external libraries" FORCE)

SET (HDFEOS_ALLOW_EXTERNAL_SUPPORT "NO" CACHE STRING "Allow External Library Building" FORCE)

SET (HDF4_PACKAGE_NAME "hdf4" CACHE STRING "Name of HDF4 package" FORCE)

SET (ZLIB_PACKAGE_NAME "zlib" CACHE STRING "Name of ZLIB package" FORCE)

SET (SZIP_PACKAGE_NAME "sz" CACHE STRING "Name of SZIP package" FORCE)

SET (JPEG_PACKAGE_NAME "jpeg" CACHE STRING "Name of JPEG package" FORCE)
