{% set version = "3.0" %}

package:
  name: hdfeos2
  version: {{ version }}

source:
  # Actual source doesn't work beause you need to login
  #- url: https://git.earthdata.nasa.gov/projects/DAS/repos/hdfeos/raw/hdf-eos2-{{ version }}-src.tar.gz
  - url: https://groups.physics.ox.ac.uk/eodg/orac/orac_libraries/hdf-eos2-{{ version }}-src.tar.gz
    sha256: 3a5564b4d69b541139ff7dfdad948696cf31d9d1a6ea8af290c91a4c0ee37188
    patches:
      - SWapi.patch
      - 0001-fix-automake-files-for-linux-compatibility.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('hdfeos2', max_pin='x.xx') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf    # [not win]
    - automake    # [not win]
    - libtool     # [not win]
  host:
    - hdf4
    - zlib
    - jpeg
  run:
    - hdf4
    - zlib
    - jpeg

test:
  requires:
    - conda-build
  commands:
    - test -f ${PREFIX}/lib/libGctp.a  # [not win]
    - test -f ${PREFIX}/lib/libhdfeos.a  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://hdfeos.org/index.php
  license: PUBLIC-DOMAIN
  summary: 'Earth Observing System HDF'

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
    - orac_cc
