c_compiler:
  - gcc
c_compiler_version:
  - 11
  - 13
#  - 12
  # HDF4 won't compile with GNU14
cxx_compiler:
  - gxx
cxx_compiler_version:
  - 11
  - 13
#  - 12
channel_sources:
  - local,conda-forge
fortran_compiler:
  - gfortran
fortran_compiler_version:
  - 11
  - 13
#  - 12

fftw:
  - 3
hdf5:
  # part of a zip_keys: c_compiler_version, cxx_compiler_version,
  #                     fortran_compiler_version, hdf5, libtiff, netcdf_fortran
  - 1.12.1
  - 1.12.2
#  - 1.12.2
libnetcdf:
  - 4.8.1
libtiff:
  # part of a zip_keys: c_compiler_version, cxx_compiler_version,
  #                     fortran_compiler_version, hdf5, libtiff, netcdf_fortran
  - 4.3.0
  - 4.5.0
#  - 4.5.0
mpi:
  - nompi
  - openmpi
netcdf_fortran:
  # part of a zip_keys: c_compiler_version, cxx_compiler_version,
  #                     fortran_compiler_version, hdf5, libtiff, netcdf_fortran
  - 4.5.4
  - 4.6.0
#  - 4.6.0
numpy:
  # part of a zip_keys: python, numpy, scipy
  - 1.21.6
  - 1.22.3
  - 1.26.4
#  - 1.22.3
#  - 1.24.4
#  - 1.22.3
#  - 1.26.4
openmpi:
  - 4
perl:
  - 5.32.1
python:
  # part of a zip_keys: python, numpy, scipy
  - 3.7.* *_cpython
  - 3.10.* *_cpython
  - 3.10.* *_cpython
#  - 3.8.* *_cpython
#  - 3.8.* *_cpython
#  - 3.9.* *_cpython
#  - 3.9.* *_cpython
python_impl:
  - cpython
scipy:
  # part of a zip_keys: python, numpy, scipy
  - 1.7.3
  - 1.8.1
  - 1.14.0
#  - 1.8.1
#  - 1.10.1
#  - 1.8.1
#  - 1.13.1
zlib:
  - 1.2.11

# Tie the versions together
zip_keys:
  -
    - c_compiler_version
    - cxx_compiler_version
    - fortran_compiler_version
    - hdf5
    - libtiff
    - netcdf_fortran
  -
    - python
    - numpy
    - scipy
