{% set version = "4.0.0" %}

package:
  name: fu_liou
  version: {{ version }}

source:
  - url: https://cloudsgate2.larc.nasa.gov/fuliou/LFLCODE/Ed4_LaRC_FuLiou201501.tar.gz
    sha256: 85840956d4bd70b2c76d50bb795acaa4d9ac4cc92ce517e906928fcbb947bfbc
    patches:
      - block.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('fu_liou', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - make

test:
  requires:
    - {{ compiler('fortran') }}
  source_files:
    - Ed4_LaRC_FuLiou/testatms
    - Ed4_LaRC_FuLiou/src/simple/simple.f90
  files:
    simple.txt

about:
  home: https://www-cave.larc.nasa.gov/cgi-bin/lflcode/accesslfl.cgi
  license: OTHER
  license_file: CERESRadiativeTransferModel-OS.pdf
  summary: "Computers broadband shortwave and longwave profiles of flux"

extra:
  recipe-maintainers:
    - orac_cc
