{% set version = "4.10" %}
{% set build = 4 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: orac
  version: {{ version }}

source:
  - git_url: https://github.com/ORAC-CC/orac
    patches:
      - make.patch
  - path: activate.sh
  - path: deactivate.sh

build:
  # This might work if we ever set a release for ORAC
  #number: {{ GIT_DESCRIBE_NUMBER }}
  number: {{ build }}
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `PKG_NAME * mpi_mpich_*` for mpich
  # `PKG_NAME * mpi_*` for any mpi
  # `PKG_NAME * nompi_*` for no mpi
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  # mpi builds require the right mpi
  # non-mpi builds *do not* appear to require non-mpi builds
  # at least not always

  {% if mpi != 'nompi' %}
  {% set build_pin = mpi_prefix + '_*' %}
  {% else %}
  {% set build_pin = '' %}
  {% endif %}
  run_exports:
    - {{ pin_subpackage('orac', max_pin='x.x.x') }} {{ build_pin }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - bison
    - flex
    - make
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - eccodes
    - epr_api
    - fu_liou
    - hdfeos2
    # without this repeat reference, conda-smithy doesn't pin correctly
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - hsd_reader >=1.12
    - hsd_reader >=1.12 {{ mpi_prefix }}_*
    - libemos
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_prefix }}_*
    - nr
    - rttov
    - rttov * {{ mpi_prefix }}_*
    - seviri_util >=1.02
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - eccodes
    - epr_api
    - fu_liou
    - hdfeos2
    - hdf5 * {{ mpi_prefix }}_*
    - hsd_reader >=1.12 {{ mpi_prefix }}_*
    - libemos
    - netcdf-fortran * {{ mpi_prefix }}_*
    - nr
    - rttov * {{ mpi_prefix }}_*
    - seviri_util >=1.02

test:
  commands:
    - test -f ${PREFIX}/lib/liborac_common.a
    - test -f ${PREFIX}/lib/libpreproc.a
    - test -f ${PREFIX}/lib/liborac.a
    - test -f ${PREFIX}/lib/libpostproc.a
    - test -f ${PREFIX}/bin/orac_preproc
    - test -f ${PREFIX}/bin/orac
    - test -f ${PREFIX}/bin/orac_postproc

about:
  home: https://github.com/ORAC-CC/orac/wiki
  license: CC
  license_file: COPYING
  summary: 'Retrieval of aerosol and cloud properties from satellite imagery'

extra:
  recipe-maintainers:
    - orac_cc
