{% set version = "4.5.9" %}
# TODO: This can support OMP

package:
  name: libemos
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3473472/libemos-{{ version }}-Source.tar.gz
  sha256: e57e02c636dc8f5ccb862a103789b1e927bc985b1e0f2b05abf4f64e86d2f67f
  patches:
    - init.patch
    - cmake.patch
    - tables.patch

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: True
  run_exports:
    - {{ pin_subpackage('libemos', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
  host:
    - eccodes <2.28.0
    - fftw
    - jpeg
    - libnetcdf
    - netcdf-fortran
    - hdf4
    - hdf5
  run:
    - eccodes <2.28.0
    - fftw

test:
  commands:
    - test -f ${PREFIX}/lib/libemos.a [not win]
    - test -f ${PREFIX}/lib/libemosR64.a [not win]
    - libemos_version

about:
  doc_url: https://software.ecmwf.int/wiki/display/EMOS/Using+EMOSLIB
  home: https://software.ecmwf.int/wiki/display/EMOS/Releases
  license: APACHE
  license_file: LICENSE
  summary: 'Interpolation library'

extra:
  recipe_maintainers:
    - orac_cc
