{% set version = "1.13" %}
{% set build = 2 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: hsd_reader
  version: {{ version }}

source:
  - git_url: https://github.com/simonrp84/Himawari_HSD_Reader
  - path: make.inc
    patches:
  {% if mpi != "nompi" %}
      - env.patch
  {% else %}
      - env_nompi.patch
  {% endif %}
  - path: Makefile

build:
  number: {{ build }}
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `PKG_NAME * mpi_mpich_*` for mpich
  # `PKG_NAME * mpi_*` for any mpi
  # `PKG_NAME * nompi_*` for no mpi
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  # mpi builds require the right mpi
  # non-mpi builds *do not* appear to require non-mpi builds
  # at least not always

  {% if mpi != 'nompi' %}
  {% set build_pin = mpi_prefix + '_*' %}
  {% else %}
  {% set build_pin = '' %}
  {% endif %}
  run_exports:
    - {{ pin_subpackage('hsd_reader', max_pin='x.x') }} {{ build_pin }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_prefix }}_*
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf * {{ mpi_prefix }}_*
    - netcdf-fortran * {{ mpi_prefix }}_*

test:
  commands:
    - test -f ${PREFIX}/lib/libhimawari_util.a
    - test -f ${PREFIX}/lib/solar_util.a
    - AHI -h

about:
  home: https://github.com/simonrp84
  license: CC
  license_file: License.md
  summary: "A reader for data from Japan's Himawari satellite"

extra:
  recipe-maintainers:
    - orac_cc
