{% set version = "2.0.1" %}
{% set build = 1 %}

{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# deprioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: nr
  version: {{ version }}

source:
  - url: https://eodg.atm.ox.ac.uk/user/povey/nr.tar.gz
    sha256: 71d2a21132742b458e05b88dedc4489bb0c160a3d7883add03a18109ed93c25e
    patches:
      - data.patch
      - shoot.patch
      - Makefile.patch
  {% if mpi == 'nompi' %}
      - nompi.patch
  {% endif %}

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage('nr', max_pin='x.x.x') }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `netcdf-fortran * mpi_mpich_*` for mpich
  # `netcdf-fortran * mpi_*` for any mpi
  # `netcdf-fortran * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libnr.a

about:
  home: http://numerical.recipes/
  license: PROPRIETARY
  license_file: LICENSE
  summary: 'Example numerical algorithms'

extra:
  recipe_maintainers:
    - orac_cc
