#!/bin/bash
#set -e

ROUTINES=(
        addint \
        airy \
        amebsa \
        amoeba \
        amotry \
        amotsa \
        anneal \
        anorm2 \
        arcmak \
        arcode \
        arcsum \
        asolve \
        atimes \
        avevar \
        balanc \
        banbks \
        bandec \
        banmul \
        bcucof \
        bcuint \
        beschb \
        bessi \
        bessi0 \
        bessi1 \
        bessik \
        bessj \
        bessj0 \
        bessj1 \
        bessjy \
        bessk \
        bessk0 \
        bessk1 \
        bessy \
        bessy0 \
        bessy1 \
        beta \
        betacf \
        betai \
        bico \
        bksub \
        bnldev \
        brent \
        broydn \
        bsstep \
        caldat \
        chder \
        chebev \
        chebft \
        chebpc \
        chint \
        chixy \
        choldc \
        cholsl \
        chsone \
        chstwo \
        cisi \
        cntab1 \
        cntab2 \
        convlv \
        copy \
        correl \
        cosft1 \
        cosft2 \
        covsrt \
        crank \
        cyclic \
        daub4 \
        dawson \
        dbrent \
        ddpoly \
        decchk \
        df1dim \
        dfour1 \
        dfpmin \
        dfridr \
        dftcor \
        dftint \
        difeq \
        dpythag \
        drealft \
        dsprsax \
        dsprstx \
        dsvbksb \
        dsvdcmp \
        eclass \
        eclazz \
        ei \
        eigsrt \
        elle \
        ellf \
        ellpi \
        elmhes \
        erf \
        erfc \
        erfcc \
        eulsum \
        evlmem \
        expdev \
        expint \
        f1dim \
        factln \
        factrl \
        fasper \
        fdjac \
        fgauss \
        fill0 \
        fit \
        fitexy \
        fixrts \
        fleg \
        flmoon \
        fmin \
        four1 \
        fourew \
        fourfs \
        fourn \
        fpoly \
        fred2 \
        fredin \
        frenel \
        frprmn \
        ftest \
        gamdev \
        gammln \
        gammp \
        gammq \
        gasdev \
        gaucof \
        gauher \
        gaujac \
        gaulag \
        gauleg \
        gaussj \
        gcf \
        golden \
        gser \
        hpsel \
        hpsort \
        hqr \
        hufapp \
        hufdec \
        hufenc \
        hufmak \
        hunt \
        hypdrv \
        hypgeo \
        hypser \
        icrc \
        icrc1 \
        igray \
        iindexx \
        indexx \
        interp \
        irbit1 \
        irbit2 \
        jacobi \
        jacobn \
        julday \
        kendl1 \
        kendl2 \
        kermom \
        ks2d1s \
        ks2d2s \
        ksone \
        kstwo \
        laguer \
        lfit \
        linbcg \
        linmin \
        lnsrch \
        locate \
        lop \
        lubksb \
        ludcmp \
        machar \
        maloc \
        matadd \
        matsub \
        medfit \
        memcof \
        metrop \
        mgfas \
        mglin \
        midexp \
        midinf \
        midpnt \
        midsql \
        midsqu \
        miser \
        mmid \
        mnbrak \
        mnewt \
        moment \
        mp2dfr \
        mpdiv \
        mpinv \
        mpmul \
        mpops \
        mppi \
        mprove \
        mpsqrt \
        mrqcof \
        mrqmin \
        newt \
        odeint \
        orthog \
        pade \
        pccheb \
        pcshft \
        pearsn \
        period \
        piksr2 \
        piksrt \
        pinvs \
        plgndr \
        poidev \
        polcoe \
        polcof \
        poldiv \
        polin2 \
        polint \
        powell \
        predic \
        probks \
        psdes \
        pwt \
        pwtset \
        pythag \
        pzextr \
        qgaus \
        qrdcmp \
        qromb \
        qromo \
        qroot \
        qrsolv \
        qrupdt \
        qsimp \
        qtrap \
        quad3d \
        quadct \
        quadmx \
        quadvl \
        ran0 \
        ran1 \
        ran2 \
        ran3 \
        ran4 \
        rank \
        ranpt \
        ratint \
        ratlsq \
        ratval \
        rc \
        rd \
        realft \
        rebin \
        red \
        relax \
        relax2 \
        resid \
        revcst \
        revers \
        rf \
        rj \
        rk4 \
        rkck \
        rkdumb \
        rkqs \
        rlft3 \
        rofunc \
        rotate \
        rsolv \
        rstrct \
        rtbis \
        rtflsp \
        rtnewt \
        rtsafe \
        rtsec \
        rzextr \
        savgol \
        scrsho \
        select \
        selip \
        shell \
        shoot \
        shootf \
        simp1 \
        simp2 \
        simp3 \
        simplx \
        simpr \
        sinft \
        slvsm2 \
        slvsml \
        sncndn \
        snrm \
        sobseq \
        solvde \
        sor \
        sort \
        sort2 \
        sort3 \
        spctrm \
        spear \
        sphbes \
        splie2 \
        splin2 \
        spline \
        splint \
        spread \
        sprsax \
        sprsin \
        sprspm \
        sprstm \
        sprstp \
        sprstx \
        stifbs \
        stiff \
        stoerm \
        svbksb \
        svdcmp \
        svdfit \
        svdvar \
        toeplz \
        tptest \
        tqli \
        trapzd \
        tred2 \
        tridag \
        trncst \
        trnspt \
        ttest \
        tutest \
        twofft \
        vander \
        vegas \
        voltra \
        wt1 \
        wtn \
        wwghts \
        zbrac \
        zbrak \
        zbrent \
        zrhqr \
        zriddr \
        zroots \
        )

KEYS=$(nm ${PREFIX}/lib/libnr.a)
for F in "${FILES[@]}"; do
    if ! echo $KEYS | grep ${F}_ > /dev/null; then
        echo $F
        exit 1
    fi
done
