{% set version = "13.1" %}
{% set build = 1 %}

{% set mpi = mpi or 'nompi' %}

package:
  name: rttov
  version: {{ version }}

source:
  # Can't use this as the contents change with each download
  #url: https://www.nwpsaf.eu/site/user/acpovey/?profiletab=downloadtab&fn=download&fname=RTTOV%20v12
  url: http://eodg.atm.ox.ac.uk/user/povey/rttov{{ version|replace('.','') }}.tar.xz
  sha256: f3bec1ca3ba952bc49e19d851144f9d51126bfe59f473be4992eac0b3366dbb2
  patches:
    - conda.patch
    - arch.patch
    - loop.patch

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage('rttov', max_pin='x.x') }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `rttov * mpi_mpich_*` for mpich
  # `rttov * mpi_*` for any mpi
  # `rttov * nompi_*` for no mpi
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - numpy {{ numpy }}
    - perl
    - python {{ python }}
  host:
    - python
    - numpy
    # need to list hdf5 and libnetcdf twice to get version pinning from
    # conda_build_config and build pinning from {{ mpi_prefix }}
    - {{ mpi }} # [mpi != 'nompi']
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_prefix }}_*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }} # [mpi != 'nompi']
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf * {{ mpi_prefix }}_*
    - netcdf-fortran * {{ mpi_prefix }}_*

test:
  requires:
    - perl
  script_env:
    - RTTOV_FILES

about:
  home: https://www.nwpsaf.eu/site/software/rttov/
  license: PROPRIETARY
  summary: 'A very fast radiative transfer model for spectrometers and interferometers'

extra:
  recipe-maintainers:
    - orac_cc
