{% set version = "13.0" %}
{% set build = 1 %}

{% set mpi = mpi or 'nompi' %}

package:
  name: rttov
  version: {{ version }}

source:
  # Can't use this as the contents change with each download
  #url: https://www.nwpsaf.eu/site/user/acpovey/?profiletab=downloadtab&fn=download&fname=RTTOV%20v12
  url: http://groups.physics.ox.ac.uk/eodg/orac/orac_libraries/rttov130.tar.xz
  sha256: b287e9f114509acfedc6b37cca861d106945b1de0ecfc4cb9346bb4ee1bc86e4
  patches:
    - local.patch
    - arch.patch

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage('rttov', max_pin='x.x.x') }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `netcdf-fortran * mpi_mpich_*` for mpich
  # `netcdf-fortran * mpi_*` for any mpi
  # `netcdf-fortran * nompi_*` for no mpi
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - numpy
    - perl
    - python
  host:
    - lapack
    - python
    - numpy
    # need to list hdf5 and libnetcdf twice to get version pinning from
    # conda_build_config and build pinning from {{ mpi_prefix }}
    - {{ mpi }} # [mpi != 'nompi']
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_prefix }}_*
  run:
    - lapack
    - python
    - numpy
    - {{ mpi }} # [mpi != 'nompi']
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf * {{ mpi_prefix }}_*
    - netcdf-fortran * {{ mpi_prefix }}_*

test:
  requires:
    - perl
  script_env:
    - RTTOV_FILES

about:
  home: https://www.nwpsaf.eu/site/software/rttov/
  license: PROPRIETARY
  summary: 'A very fast radiative transfer model for spectrometers and interferometers'

extra:
  recipe-maintainers:
    - orac_cc
