C-----------------------------------------------------------------------
C !F77-INC
C
C !DESCRIPTION:
C    Include file for UW MODIS Algorithm Platform Name
C
C !INPUT PARAMETERS:
C    None
C
C !OUTPUT PARAMETERS:
C    None
C
C !REVISION HISTORY:
C
C !TEAM-UNIQUE HEADER:
C    Developed by the MODIS Group, CIMSS/SSEC, UW-Madison.
C
C !END
C-----------------------------------------------------------------------

      character*5 platform_name
      common / platform_name_common / platform_name
