{% set version = "4.5.3" %}
{% set build = 0 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: netcdf-fortran
  version: {{ version }}

source:
  git_url: https://github.com/Unidata/netcdf-fortran
  git_rev: {{ "v" + version }}

build:
  number: {{ build }}
  merge_build_host: true

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `netcdf-fortran * mpi_mpich_*` for mpich
  # `netcdf-fortran * mpi_*` for any mpi
  # `netcdf-fortran * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('netcdf-fortran', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - libtool     # [not win]
    - automake    # [not win]
    - autoconf    # [not win]
    # need to list hdf5 and libnetcdf twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']

test:
  requires:
    - {{ compiler('fortran') }}
  commands:
    - nf-config --all  # FIXME: no nf-config for cmake
    - test -f $(nc-config --fc)
    - test -f ${PREFIX}/lib/libnetcdff.a  # [unix]

about:
  home: https://github.com/Unidata/netcdf-fortran
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  license_file: COPYRIGHT
  summary: 'Unidata NetCDF Fortran Library'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - beckermr
    - xylar
